### ISSUE TITLE
Make the client mockable with Java mocking frameworks

### ISSUE THREAD

**Issue by akkie** [playframework/play-ws#108]
### Play WS Version (2.5.x / etc)
1.0.0-M8

### API (Scala / Java / Neither / Both)
Scala

### Expected Behavior

It should be able to mock the client with Java mocking libraries like mockito, EasyMock or JMock.

### Actual Behavior

The following code doesn't compile:

```scala
val wsRequest = mock[WSRequest]
val wsResponse = mock[WSResponse]

wsResponse.json throws new RuntimeException("Unexpected character ('<' (code 60))")
wsResponse.body returns "<html></html>"
wsRequest.withHeaders(any) returns wsRequest
wsRequest.post[Map[String, Seq[String]]](any)(any) returns Future.successful(wsResponse)
```

```
/home/travis/build/mohiva/play-silhouette/silhouette/test/com/mohiva/play/silhouette/impl/providers/OAuth2ProviderSpec.scala:274: type mismatch;
[error]  found   : this.wsRequest.type (with underlying type play.api.libs.ws.WSRequest)
[error]  required: this.wsRequest.Self
[error]       wsRequest.withHeaders(any) returns wsRequest

/home/travis/build/mohiva/play-silhouette/silhouette/test/com/mohiva/play/silhouette/impl/providers/OAuth2ProviderSpec.scala:275: type mismatch;
[error]  found   : this.wsResponse.type (with underlying type play.api.libs.ws.WSResponse)
[error]  required: this.wsRequest.Response
[error]       wsRequest.post[Map[String, Seq[String]]](any)(any) returns Future.successful(wsResponse)
```

### Reproducible Test Case

https://github.com/mohiva/play-silhouette/pull/509

### Links

https://groups.google.com/forum/#!topic/play-framework/mYPRPbfa8Uk

### Notes

Both Scala testing libraries support mocking with Java mocking frameworks. [ScalaTest](http://www.scalatest.org/user_guide/testing_with_mock_objects#easyMock) supports one Scala and three Java mocking frameworks. [Specs2](https://etorreborre.github.io/specs2/guide/SPECS2-3.4/org.specs2.guide.UseMockito.html) provides syntactic sugar for mockito. This shows that using Java mocking frameworks in the Scala world is a preferred method.

Switching to [play-mockws](https://github.com/leanovate/play-mockws) as suggested by @wsargent , isn't a good solution for a play related library, because then the library is bound to the release cycle of that play related dependency.

**Comment by wsargent** [comment]
The other option is to add a mock implementation directly if possible.

**Comment by akkie** [comment]
@wsargent Could you please illustrate this a bit more? Do you mean based on the `play-ws` traits without the typing stuff (which I think isn't possible) or a complete implementation like `play-mockws`? Or do you mean a wrapper around the `play-ws` functionality`? But then I have to test this wrapper too, which isn't easily possible.

**Comment by wsargent** [comment]
Basically -- taking play-mockws and merging it into play-ws.  Then the release cycle problem goes away.

**Comment by akkie** [comment]
This would be an option. But is it worth to implement a mock implementation instead of using types based on generics? I don't know the problems you had with the generic implementation. Does it generally not work or is it only ugly?

**Comment by akkie** [comment]
@wsargent I need to know if there is a solution for the final Play 2.6 release, so that I can proceed with my tasks. A short info would be great!

**Comment by wsargent** [comment]
Hi @akkie can you provide a small self-contained project as described in https://groups.google.com/d/msg/play-framework/mYPRPbfa8Uk/DFl3ONJcAgAJ ?

**Comment by wsargent** [comment]
@akkie This unit test seems to work fine:

```scala
package play.api.libs.ws

import org.specs2.mock.Mockito
import org.specs2.mutable.Specification

import scala.concurrent.Future

class MockitoSpec extends Specification with Mockito {

  trait WSRequest extends StandaloneWSRequest {
    type Self = StandaloneWSRequest
    type Response = StandaloneWSResponse
  }

  "wsrequest" should {

    "be mockable" in {
      val wsRequest = mock[WSRequest]
      val wsResponse = mock[StandaloneWSResponse]

      wsResponse.json throws new RuntimeException("Unexpected character ('<' (code 60))")
      wsResponse.body returns "<html></html>"
      wsRequest.withHeaders(any) returns wsRequest
      wsRequest.post[Map[String, Seq[String]]](any)(any) returns Future.successful(wsResponse)

      success
    }
  }
}
```

**Comment by akkie** [comment]
@wsargent Yes it works, but normally you deal with the `WSClient` and not only with the request and the response parts. So it's possible to define your own request trait, but with the currently provided methods, you cannot assign this custom class to your `WSClient.url` method, which is mostly the entry point in your implementations.

But, you brought me to an idea. From the beginning, I've used the [HTTPLayer](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/api/util/HTTPLayer.scala#L25) trait to provide a mockable implementation for the previously provided global `WSClient` object. And this allows my to create a [MockHTTPLayer](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/api/util/HTTPLayer.scala#L77) which uses a custom [MockWSRequest](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/api/util/HTTPLayer.scala#L69). This works now as expected!

**Comment by wsargent** [comment]
Awesome!

**Comment by raphaelbauer** [comment]
Just as a quick feedback. We converted our projects to Play 2.6 and the latest wsClient (lots and lots of code, lots and lots of mocks of wsClient stuff). 

And all worked perfectly fine.

👍

**Comment by marcospereira** [comment]
Thanks for the feedback, @raphaelbauer!

**Comment by marcospereira** [comment]
Hi @jhz7,

Our [forums](https://discuss.playframework.com) would be a better place to discuss this. It would be good if you can share some code there too, and the JSON Play WS is getting. Is it valid? What [JSONLint](https://jsonlint.com/) says about it?

Best.
