### ISSUE TITLE
Should preserve existing headers when using withBody

### ISSUE THREAD

**Issue by yangbajing** [playframework/play-ws#113]
### Play WS Version (2.6.x / etc)

1.0.0-M8

### API (Scala / Java / Neither / Both)

StandaloneAhcWSRequest.withBodyAndContentType

### Expected Behavior

request.addHttpHeaders(
        "hl-app-id" -> appId,
        "hl-timestamp" -> timestamp,
        "hl-echo-str" -> echoStr,
        "hl-access-token" -> accessToken
      )

Send the HTTP Headers I have set the custom header.

### Actual Behavior

Send the HTTP Headers and I did not set the value.

I think here: `withBody(wsBody).withHttpHeaders(HttpHeaders.Names.CONTENT_TYPE, contentType)`
Should be amended as follows: `withBody(wsBody).addHttpHeaders(HttpHeaders.Names.CONTENT_TYPE, contentType)`

**Comment by wsargent** [comment]
I'm not sure I understand.  There is no withBodyAndContentType method in Play WS.

**Comment by marcospereira** [comment]
@wsargent I think the problem is here:

https://github.com/playframework/play-ws/blob/master/play-ahc-ws-standalone/src/main/scala/play/api/libs/ws/ahc/StandaloneAhcWSRequest.scala#L176-L182

It is a private method used by `withBody`. The `else` clause should be using `addHttpHeader` instead.
