### ISSUE TITLE
response.getUri() is missing

### ISSUE THREAD

**Issue by wsargent** [playframework/play-ws#169]
play.libs.ws.StandaloneWsResponse.getUri() is missing -- this is a useful method because it shows what the final URL was after several redirects in the browser.

**Comment by dmitraver** [comment]
hi, I can pick this one

**Comment by albuch** [comment]
The deletion of `getUri()` is a breaking change that was missed in the Play 2.6 migration guide as well.

**Comment by david-nossebro** [comment]
Why was this issue closed? I still see the same issue and have not found any solution.
