### ISSUE TITLE
Suboptimal `withHttpHeaders` naming migration can lead to subtle bugs

### ISSUE THREAD

**Issue by mriehl** [playframework/play-ws#191]
### Play WS Version (2.5.x / etc)

2.6.x

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Linux 4.13.0-1

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

hotspot 1.8.0_144

### Expected Behavior

In 2.5.x `wsClient.withHeaders(String*)` could be used to add additional HTTP headers.
In 2.6.x at first glance, `wsClient.withHttpHeaders` SEEMS to be a suitable upgrade path candidate (but isn't)

### Actual Behavior
In 2.6.x `wsClient.withHttpHeaders` discards all the current http headers and only adds the passed varargs as http headers.

The replacement is actually `addHttpHeaders`.

This kind of naming change is really terrible.
It's easy to get wrong while migrating from 2.5.x to 2.6.x and it can lead to the weirdest issues.
Arguably the new name is much better, so maybe all it needs is a mention in the upgrade guide if it's possible to update it?

**Comment by marcospereira** [comment]
Hi @mriehl, thanks for the clear feedback.

I agree with you that we can better describe this change in our migration guide. The correct place to add it is:

https://github.com/playframework/playframework/blob/master/documentation/manual/releases/release26/migration26/WSMigration26.md

A pull request would be very welcomed. ;-)
