### ISSUE TITLE
Upgrade to AsyncHttpClient 2.1.0

### ISSUE THREAD

**Issue by richdougherty** [playframework/play-ws#199]
AsyncHttpClient has just released the 2.1.0 RC. We should test this out and get any feedback back to the AHC devs.

https://twitter.com/AsyncHttpClient/status/936341654562398208

**Comment by richdougherty** [comment]
Cc @slandelle, @wsargent.

**Comment by slandelle** [comment]
Maybe this would help: https://abi-laboratory.pro/java/tracker/timeline/async-http-client/

**Comment by fatihi-sky** [comment]
I upgraded AsyncHttpClient to 2.4.4 to be able to benefit from ClientDetails object they exposed to get connection metrics. 
There are some major changes tho, I wanted to start a discussion here(https://groups.google.com/forum/#!forum/play-framework-dev) to get feedback for couple of points, but seems like no one is looking for membership approvals for that group for a while. 
Any suggestions how to proceed on that?

**Comment by wsargent** [comment]
@fatihi-sky we are using http://discuss.playframework.com now, so I would start up a topic there.

**Comment by wsargent** [comment]
Fixed by https://github.com/playframework/play-ws/pull/289
