### ISSUE TITLE
play.libs.ws.StandaloneWSRequest lacks getMethod

### ISSUE THREAD

**Issue by wsargent** [playframework/play-ws#231]
The Scala version has it:

https://github.com/playframework/play-ws/blob/master/play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSRequest.scala#L43

but there is no Java version, only a `setMethod`:

https://github.com/playframework/play-ws/blob/master/play-ws-standalone/src/main/java/play/libs/ws/StandaloneWSRequest.java#L144

**Comment by AlejandroRivera** [comment]
There's a PR that already introduces this missing method: #178 
More specifically: https://github.com/playframework/play-ws/pull/178/files#diff-81cde33a396d318cacb479ddba9015e9

However, IMHO, introducing the missing methods should not be blocked by this PR which has been open since July 2017.
