### ISSUE TITLE
OAuth 1 Signature Fails with Empty Map Body,

### ISSUE THREAD

**Issue by mbseid** [playframework/play-ws#257]
We recently upgraded from Play Framework 2.5 to 2.6 and noticed an odd error with the OAuth 1 signature. When posting a request with an empty body, `Map.empty[String, Seq[String]]`, the twitter requests fails with the following response: `Could not authenticate you.`.  If the body was not empty, or using the `EmptyBody` object, things work as expected.

### Are you looking for help?
No

### Play WS Version (2.5.x / etc)
2.6

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Mac OSX 10.13.2

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

### Expected Behavior

1. Create an OAuth Signature
2. Send a Post Request with an empty body
3. Successful Request

### Actual Behavior

1. Create an OAuth Signature
2. Send a Post Request with an empty body
3. Request Error, OAuth Signature Wrong

### Reproducible Test Case

Request Fails:
```
val oauthCalculator = OAuthCalculator(Key, rt)
val wsRequest = wsClient.url(request.url).sign(oauthCalculator)
val emptyMap = Map.empty[String, Seq[String]]
wsRequest.post(emptyMap)
```

Requests Succeeds
```
val oauthCalculator = OAuthCalculator(Key, rt)
val wsRequest = wsClient.url(request.url).sign(oauthCalculator)
wsRequest.post(EmptyBody)
```

**Comment by gmethvin** [comment]
#258 should fix it. For an empty map we're appending a single POST param with empty key/value pair when we should be appending nothing.
