### ISSUE TITLE
How to add standalone version to SBT project ?

### ISSUE THREAD

**Issue by Vachman** [playframework/play-ws#27]
Hi, help me please. Maybe i am doing something wrong,
but  i can't even install this lib. 

I am adding this to build.sbt
`libraryDependencies += "com.typesafe.play" %% "play-ahc-ws-standalone" % "2.6.0-M1"`
 
and getting:
```
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.play#play-ahc-ws_2.11;2.6.0-M1: not found 
```
 
Also i tried to clone this repo and open `sbt console` in templeate/standalone project,
but i am still getting the same error.

**Comment by wsargent** [comment]
This project has not been released yet.  Please check back later.
