### ISSUE TITLE
javax.annotation classes being added to shaded jar

### ISSUE THREAD

**Issue by renatocaval** [playframework/play-ws#419]
async-http-client is now including `javax.annotation` (see https://github.com/AsyncHttpClient/async-http-client/issues/1541 and https://github.com/AsyncHttpClient/async-http-client/commit/e270f787aa770298e15a425623558d6587a067bb). 

We need to investigate it further why that specific dependency is not been treated as a transitive deps and is being included in the shaded jar. 

Because `javax.activation` classes are now in the shaded jar, this can caused Java Linkage errors at runtime.

**Comment by dwijnand** [comment]
> caused Java Linkage errors at runtime

where?
