### ISSUE TITLE
Where does AHC come from in standalone code?

### ISSUE THREAD

**Issue by fancellu** [playframework/play-ws#433]
https://github.com/playframework/play-ws#scala-1

Where does ahc come from?

i.e. ```import play.api.libs.ws.ahc._```

I have the following in my sbt

```libraryDependencies += "com.typesafe.play" %% "play-ws-standalone" % "2.1.2"```

But this doesn't pull in play.api.libs.ws.ahc

This seems to fix it

```libraryDependencies += "com.typesafe.play" %% "play-ahc-ws" % "2.8.0"```

Or should I be doing something else?

**Comment by wsargent** [comment]
Please see https://github.com/playframework/play-ws/blob/master/README.md#getting-started

**Comment by fancellu** [comment]
What are you pointing me to? 

I pulled in ```"com.typesafe.play" %% "play-ws-standalone" % "2.1.2"

but that wasn't enough

So I had to pull in ```"com.typesafe.play" %% "play-ahc-ws" % "2.8.0"```

Am I not seeing where this was specified?

Thanks

**Comment by marcospereira** [comment]
Hey @fancellu, 

I believe will were pointing you to the section of README.md file that documents the right dependency you need to add:

```scala
libraryDependencies += "com.typesafe.play" %% "play-ahc-ws-standalone" % "2.1.2"
```

You are adding `play-ws-standalone` which is like a SPI while `play-ahc-ws-standalone` is the current implementation that contains `play.api.libs.ws.ahc` package. When you add Play's `play-ahc-ws` it transitively adds the standalone version, and that is why things were working for you then.

Anyhow, our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play and its modules, not for general discussion and getting help. Given that, I'm closing this.

Best.
