### ISSUE TITLE
Branch `2.1.x` is useless

### ISSUE THREAD

**Issue by ignasi35** [playframework/play-ws#481]
Having a branch `2.1.x` is misleading: `master` is the branch to release `2.1.x` versions and we only need `2.0.x` as stable branches in the `2.x.y` series.

If we have a couple 👍🏼 I'll remove `2.1.x` from the branches list as that's confusing.

**Comment by ignasi35** [comment]
ping @cchantep @renatocaval  @marcospereira

**Comment by mkurz** [comment]
Outdated, we just released 2.1.3 from the 2.1.x branch. If I recall correctly, Marcos force pushed the 2.1.x branch to the correct location.
