### ISSUE TITLE
Replace AHC by Akka Client API (akka-http-core)

### ISSUE THREAD

**Issue by limpid-kzonix** [playframework/play-ws#578]
This one is supposed to be under GitHub discussions 
AHC is basically a dead project now since there's no longer an active maintainer
Is a reason to revamp this play-ws library with Akka HTTP Client API as underlying implementation?

**Comment by ihostage** [comment]
Looks like a duplicate of #34

**Comment by ihostage** [comment]
Moreover, @2m already started work some year ago in #208. 
Maybe in the future, somebody continues this work.
