### ISSUE TITLE
Add Scala 3 support

### ISSUE THREAD

**Issue by SethTisue** [playframework/play-ws#598]
would a volunteer like to attempt this? it would be helpful even just to have a failing draft PR that shows where the next roadblock is, and then we could chip away it from there

I published ssl-config and cachecontrol today for Scala 3, so that helps

#590 should be merged before any attempt is made at this

**Comment by mkurz** [comment]
@SethTisue As you probably have noticed, #590 got merged.

**Comment by mkurz** [comment]
@xuwei-k Do you can/want to help?

**Comment by xuwei-k** [comment]
Could not compile play-ws with Scala 3 due to https://github.com/lampepfl/dotty/issues/12731 😢 

https://github.com/playframework/play-ws/blob/c8429038edce378626996467f33301a7c1b2ad03/play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSRequest.scala#L23

**Comment by wsargent** [comment]
I thought this was very clever of me at the time.

**Comment by mkurz** [comment]
@xuwei-k @SethTisue did you see [these 2 comments](https://github.com/lampepfl/dotty/issues/12731#issuecomment-907134727)?  Replacing F-bounds by intersection types? WDYT? Also see https://github.com/lampepfl/dotty/issues/13133 and https://github.com/lampepfl/dotty/issues/10638#issuecomment-739151145

> If you have an F-bounded type `T <: F[T]` simply replace it with `T`. Then everywhere `T` is used, replace it with `T & F[T]`.

**Comment by xuwei-k** [comment]
https://github.com/playframework/play-ws/pull/604

**Comment by SethTisue** [comment]
@mkurz I'm sorry but I don't know what to think about that, and I don't feel that have time to dig into it. :-/

**Comment by mkurz** [comment]
@SethTisue Currently not so much time as well (coming weeks)...

**Comment by ihostage** [comment]
Was implemented in #604 but has some comments https://github.com/playframework/play-ws/pull/604#pullrequestreview-906492465 from @mkurz

**Comment by xuwei-k** [comment]
🎉 

- https://github.com/playframework/play-ws/releases/tag/2.2.0-M2
- https://repo1.maven.org/maven2/com/typesafe/play/play-ws-standalone_3/
