### ISSUE TITLE
Add Sonatype-based publishing

### ISSUE THREAD

**Issue by SethTisue** [playframework/play-ws#600]
using sbt-ci-release. I can use my recent PRs in other playframework/* repos as a model

**Comment by SethTisue** [comment]
Not sure if there's any real need for this unless/until someone decides to tackle #598 (Scala 3 support)

**Comment by mkurz** [comment]
A new release of play-ws unlocks https://github.com/playframework/playframework/pull/10901

**Comment by mkurz** [comment]
See https://github.com/playframework/playframework/pull/10901#issuecomment-892213840

**Comment by SethTisue** [comment]
Oh, sorry, I should have remembered that. Okay, I'll tackle this soon-ish, then.

**Comment by mkurz** [comment]
Whenever you have time, I am not under pressure.

**Comment by SethTisue** [comment]
I've unassigned myself now that the handoff of Play to Open Collective is underway.

**Comment by SethTisue** [comment]
@mkurz is this done now, after #631?
