### ISSUE TITLE
Inconsistent shading of asynchttpclient

### ISSUE THREAD

**Issue by bulkazszynka** [playframework/play-ws#862]
2.X line of the playframework includes the asynchttpclient library having packages prefixed with play.shaded.ahc. However, in version 3.0 this prefix has been removed from 3 class files i.e.

-  com.typesafe.netty.CancelledSubscriber
- com.typesafe.netty.HandlerPublisher
- com.typesafe.netty.HandlerSubscriber

Such inconsistency may lead to compatibility issues for users who upgrade from version 2.9 to 3.0.

**Comment by mkurz** [comment]
Actually my last comment was not entirely correct, the correct package name still should be `com.typesafe.netty` prefixed with `play.shaded.ahc.*`, resulting in `play.shaded.ahc.com.typesafe.netty.*`. Fixed in now in # #863, see comments over there for more explanation.

**Comment by SheliakLyr** [comment]
Hi. We are also impacted by this problem. Is there a release planned with the fix?

**Comment by mkurz** [comment]
> Hi. We are also impacted by this problem. Is there a release planned with the fix?

Actually there is nothing holding back a new patch release, so I can do that now.

**Comment by mkurz** [comment]
3.0.2 released: https://github.com/playframework/play-ws/releases/tag/3.0.2

If you are using the Play Framework, you can upgrade yourself until Play 3.0.3 is released:

```sbt
...
libraryDependencies += ws // or javaWs

// Use latest play-ws release (can be removed when Play 3.0.3 is released)
val playWS = "3.0.2"
libraryDependencies ++= Seq(
  "org.playframework" %% "play-ahc-ws-standalone" % playWS,
  "org.playframework" %% "play-ws-standalone-json" % playWS,
  "org.playframework" %% "play-ws-standalone-xml" % playWS,
  "org.playframework" % "shaded-asynchttpclient" % playWS,
  "org.playframework" % "shaded-oauth" % playWS,
)
...
```
