### ISSUE TITLE
Exceptions when using together with AsyncHttpClient

### ISSUE THREAD

**Issue by domdorn** [playframework/play-ws#87]
Sorry for cross-posting. I've written down the details of this issue at: 
https://github.com/playframework/playframework/issues/7056

It looks like (at least in my Play 2.6.0-M1 app) that the shaded AsyncHttpClientDefaults class reads the ahc-default.properties that are pulled in from the non-shaded version on my classpath. 

The issue probably comes from 
https://github.com/AsyncHttpClient/async-http-client/blob/async-http-client-project-2.0.27/client/src/main/java/org/asynchttpclient/config/AsyncHttpClientConfigHelper.java#L47

Where the current ThreadContext Classloader is used to lookup the properties instead a classloader based on the current class (which would then find the ahc-default.properties with the play.shaded prefix.

**Comment by domdorn** [comment]
So what we would need to do is to also rename the ahc-default.properties to something like play.shaded-ahc-default.properties and replace references to it.
I can provide a PR for that if that is OK for you @wsargent  / @marcospereira

**Comment by wsargent** [comment]
Yes please.

**Comment by domdorn** [comment]
Ok, unfortunately, "jar jar links" only supports changing the package name of the classes transformed. I've managed to rename the ahc-default.properties and ahc.properties files themselves, but unfortunately, references to these are hardcoded (as constants) in 
https://github.com/AsyncHttpClient/async-http-client/blob/async-http-client-project-2.0.27/client/src/main/java/org/asynchttpclient/config/AsyncHttpClientConfigHelper.java#L33
respectively in 
https://github.com/AsyncHttpClient/async-http-client/blob/async-http-client-project-2.0.27/client/src/main/java/org/asynchttpclient/config/AsyncHttpClientConfigHelper.java#L37 / https://github.com/AsyncHttpClient/async-http-client/blob/async-http-client-project-2.0.27/client/src/main/java/org/asynchttpclient/config/AsyncHttpClientConfigHelper.java#L41

Unfortunately, the whole AysncHttpClientConfigHelper is written in a way that does not really allow outside modification/configuration. We could try to exclude it in the shading process and provide our own version of it, but that feels like a rather bad hack.

**Comment by domdorn** [comment]
A alternative to shading the async-http-client on a class-file level could be to include the async-http-client project as a sbt-source-dependency .. that way it might be possible to basically take the files and rewrite them directly (and thus making also changes to the constants in AsyncHttpClientConfigHelper .. but its another "hack".

**Comment by wsargent** [comment]
workaround defined in https://github.com/playframework/playframework/issues/7056#issuecomment-285370901

https://gist.github.com/domdorn/3c80fac337ffc847650ae5f547f62c55

**Comment by wsargent** [comment]
@domdorn do you have a PR for this?

**Comment by domdorn** [comment]
@wsargent I tried to adjust the shading process, but the shading library used only allows simple byte-code changes (changing package names) -> I was unable to change the constant. 
I once did something similar with cglib, but I'm not sure we want to go down that route.

**Comment by domdorn** [comment]
Hmm... I've got an idea... what if instead of replacing the variables in the ahc.properties, we're just adding to them? 
so instead of only writing
`play.shaded.ahc.org.asynchttpclient.threadPoolName=AsyncHttpClient`
to the file, we write
```
play.shaded.ahc.org.asynchttpclient.threadPoolName=AsyncHttpClient
org.asynchttpclient.threadPoolName=AsyncHttpClient
```
to the file? That way, we still be providing the default file, and also provide our own properties. People can still change their settings in the other config file. WDYT?

**Comment by wsargent** [comment]
Okay, I can address that in a patch release.

**Comment by domdorn** [comment]
@wsargent I have a PR for this: https://github.com/playframework/play-ws/pull/149

**Comment by wsargent** [comment]
Closing by way of https://github.com/playframework/play-ws/pull/149
