### ISSUE TITLE
[2.5.x] Add API to get a single header

### ISSUE THREAD

**Issue by igmar** [playframework/play-ws#88]
Currently, in 2.5.x there is no way to get a single header from a WSRequest : The API only has getHeaders, which returns a Map<String, Collection<String>>

We can easy get a simple header from the map, but having a bit more clean API would be nice.

**Comment by wsargent** [comment]
This is only 2.6.x API though

**Comment by igmar** [comment]
Making this a 2.6.x thing would be good enough for me.
