### ISSUE TITLE
Streamed response headers are case sensitive

### ISSUE THREAD

**Issue by GithubUser8080** [playframework/play-ws#908]
When the request has .streamed(), then all methods to get headers, like response.getContentType() fail if the case is not an exact match. E.g for response `Content-Type : application/json`, response.getContentType() returns octet-stream. It only succeeds if the headers are all lowercase. Normally header matching must be case insensitive.

**Comment by mkurz** [comment]
@GithubUser8080 Just taking a quick look, maybe this line could be related?
https://github.com/playframework/play-ws/blob/1f4f1d10aac594c6476fd53b550503a98c473a18/play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSResponse.scala#L73

**Comment by GithubUser8080** [comment]
> @GithubUser8080 Just taking a quick look, maybe this line could be related?
> 
> https://github.com/playframework/play-ws/blob/1f4f1d10aac594c6476fd53b550503a98c473a18/play-ws-standalone/src/main/scala/play/api/libs/ws/StandaloneWSResponse.scala#L73

I will try to remember the exact line, but if i remember correctly, all other response types, when getting headers, return a TreeMap copy of headers with case insensitive keys. Whereas StreamedResponse getHeaders() returns the original case sensitive map of headers from the underlying response.

**Comment by GithubUser8080** [comment]
Normal response 

https://github.com/playframework/play-ws/blob/1f4f1d10aac594c6476fd53b550503a98c473a18/play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StandaloneAhcWSResponse.java#L64

Streamed response

https://github.com/playframework/play-ws/blob/1f4f1d10aac594c6476fd53b550503a98c473a18/play-ahc-ws-standalone/src/main/java/play/libs/ws/ahc/StreamedResponse.java#L66

**Comment by GithubUser8080** [comment]
Thanks

**Comment by mkurz** [comment]
@GithubUser8080 fix released:
- https://github.com/playframework/play-ws/releases/tag/2.2.9
- https://github.com/playframework/play-ws/releases/tag/3.0.5

**Comment by mkurz** [comment]
Please let me now if that works for you now, thanks!

**Comment by GithubUser8080** [comment]
> Please let me now if that works for you now, thanks!

It does, thank you for the fast response!
