### ISSUE TITLE
Fix sbt-release for sonatype publishing

### ISSUE THREAD

**Issue by wsargent** [playframework/play-ws#92]
Currently the publish to Sonatype fails, and so the artifacts are sent to staging but have to be published from the staging repository by hand (by clicking "close" and then "publish") rather than directly.

Not sure what is causing this behavior, and it's hard to fake publishing to Sonatype.

**Comment by marcospereira** [comment]
@wsargent was this fixed by #106 and #107?

**Comment by wsargent** [comment]
Yes. :-D
