### ISSUE TITLE
WSRequest should have a setCookies() method

### ISSUE THREAD

**Issue by franzgranlund** [playframework/play-ws#97]
### Play WS Version (2.5.x / etc)
Using Play WS 2.5

### API (Scala / Java / Neither / Both)
Java (don't know about Scala)

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
All I guess

### Improvement

It would be very convenient if there was a `.setCookies(List<WSCookie> cookies)` method on `WSRequest` to easily share cookies between different requests. `WSResponse` have a `.getCookies()` so it is easy getting the cookies out.

**Comment by marcospereira** [comment]
For the Scala version see #83.

Also, it could be relevant to see discussion in playframework/playframework#7016 to have consistent names here. To resume the discussion there, we decide to have something like:

1. `withCookies`: set cookies values or replace the current cookies
2. `addCookie`: add/append a new cookie.

**Comment by marcospereira** [comment]
Just a reminder to myself, if we decide to change the behavior of the existent APIs, we should update the migration guide in Play repository.

**Comment by marcospereira** [comment]
Closed by #102.
